version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pipenv install
            npm install
            pipenv run mozdownload --version latest --destination $HOME/firefox.tar.bz2
            pipenv run mozinstall --destination $HOME $HOME/firefox.tar.bz2
      - run:
          name: Build extension
          command: |
            npm run build
      - run:
          name: Run linting checks
          command: |
            npm run lint
      - run:
          name: Run automated tests
          command: |
            pipenv run test -- --firefox_bin $HOME/firefox/firefox
      - run:
          name: Package extension as XPI
          command: |
            npm run package
      - store_artifacts:
          path: web-ext-artifacts
      - store_artifacts:
          path: gecko.log
